version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      no_cache: true
    container_name: rangaone-fe-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    volumes:
      - ./.env.production:/app/.env.production:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.docker.compose.project=rangaone-fe"
      - "deployment.timestamp=${DEPLOYMENT_TIMESTAMP:-$(date +%s)}"

  nginx:
    image: nginx:alpine
    container_name: rangaone-nginx-prod
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      app:
        condition: service_healthy
    restart: unless-stopped
    labels:
      - "com.docker.compose.project=rangaone-fe"