version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.optimized
      args:
        - NODE_ENV=production
        - NEXT_TELEMETRY_DISABLED=1
        - BUILD_TIME=${BUILD_TIME:-$(date -u +"%Y-%m-%dT%H:%M:%SZ")}
    container_name: rangaone-fe-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - HOSTNAME=0.0.0.0
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - rangaone-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    labels:
      - "com.docker.compose.project=rangaone-fe"
      - "deployment.timestamp=${DEPLOYMENT_TIMESTAMP:-$(date +%s)}"
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  nginx:
    image: nginx:alpine
    container_name: rangaone-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      app:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - rangaone-network
    labels:
      - "com.docker.compose.project=rangaone-fe"

networks:
  rangaone-network:
    driver: bridge
    name: rangaone-network