version: '3.8'

services:
  app:
    image: ${IMAGE_TAG:-ghcr.io/liquidevz/rangaone-fe:latest}
    container_name: rangaone-fe-prod
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - PORT=3000
      - HOSTNAME=0.0.0.0
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - rangaone-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    labels:
      - "deployment.timestamp=${DEPLOYMENT_TIMESTAMP}"

  nginx:
    image: nginx:alpine
    container_name: rangaone-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      app:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - rangaone-network

networks:
  rangaone-network:
    driver: bridge