name: Build & Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/rangaone/htdocs/www.rangaone.finance/Rangaone_Finance

            # Ensure repo is clean & updated
            git fetch origin
            git add .
            git stash
            git reset --hard origin/main
            git checkout main
            git pull origin main

            # Ensure .env file exists (create from template or copy from secure location)
            if [ ! -f .env ]; then
              echo "Warning: .env file not found. Creating from .env.example if available."
              if [ -f .env.example ]; then
                cp .env.example .env
              fi
            fi

            # Clean Docker cache to prevent old code
            docker system prune -f
            docker builder prune -f

            # Stop and remove existing containers
            docker compose down --remove-orphans

            # Build and deploy with docker-compose (no cache)
            docker compose build --no-cache
            docker compose up -d

            # Wait for container to be healthy
            sleep 15

            # Verify deployment
            if [ "$(docker compose ps -q rangaone-fe)" ]; then
              echo "✅ Deployment successful!"
            else
              echo "❌ Deployment failed!"
              exit 1
            fi
