name: Build & Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Navigate to app directory
            cd /home/rangaone/htdocs/www.rangaone.finance/Rangaone_Finance

            # Ensure repo is clean & updated
            git fetch origin
            git reset --hard origin/main
            git checkout main
            git pull origin main

            # Stop and remove all containers from docker-compose
            docker compose down || true

            # Rebuild everything fresh and start in detached mode
            docker compose up --build -d

            echo "✅ Deployment to main branch completed successfully!"
