name: Deploy to Production

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build project
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy with Docker via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          timeout: 300s
          script: |
            # Navigate to project directory
            cd ~/htdocs/www.rangaone.finance/Rangaone_Finance || exit

            # Update code from GitHub
            if [ -d ".git" ]; then
              git reset --hard
              git clean -fd
              git pull origin master
            else
              git clone https://github.com/${{ github.repository }} .
            fi

            # Stop existing Docker container if running
            docker stop nextjs-app 2>/dev/null || true
            docker rm nextjs-app 2>/dev/null || true

            # Build and run Docker container
            docker build -t nextjs-app .
            docker run -d \
              --name nextjs-app \
              --restart unless-stopped \
              -p 3000:3000 \
              nextjs-app

            # Cleanup unused Docker images
            docker image prune -f

            echo "✅ Deployment complete!"
