name: Build & Deploy Next.js App

# Trigger only on push to master branch
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Build Next.js app
      - name: Build Next.js app
        run: npm run build

      # 5. Build Docker image on runner
      - name: Build Docker image
        run: |
          IMAGE_NAME=nextjs-app
          IMAGE_TAG=$IMAGE_NAME:latest
          docker build -t $IMAGE_TAG .
          docker save $IMAGE_TAG -o nextjs-app.tar

      # 6. Deploy Docker image to server
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            IMAGE_NAME=nextjs-app
            IMAGE_TAG=$IMAGE_NAME:latest

            # Stop old container if exists
            if [ "$(docker ps -q -f name=$IMAGE_NAME)" ]; then
              docker stop $IMAGE_NAME
              docker rm $IMAGE_NAME
            fi

            # Remove old image if exists
            if [ "$(docker images -q $IMAGE_NAME)" ]; then
              docker rmi $IMAGE_NAME -f
            fi

            # Move uploaded tar to /tmp
            mv /tmp/nextjs-app.tar /tmp/${IMAGE_NAME}.tar

            # Load Docker image
            docker load < /tmp/${IMAGE_NAME}.tar

            # Run container
            docker run -d --name $IMAGE_NAME -p 3000:3000 $IMAGE_TAG
