name: Build & Deploy Next.js App

# Trigger workflow on push to master
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Navigate to app directory
            cd /home/rangaone/htdocs/www.rangaone.finance/Rangaone_Finance

            # Ensure git repo is clean and on master
            git fetch origin
            git stash push -m "auto-stash before deploy" || true
            git reset --hard origin/master
            git checkout master
            git pull origin master

            # Docker variables
            IMAGE_NAME=nextjs-app
            CONTAINER_NAME=nextjs-app

            # Stop and remove old container if exists
            if [ "$(docker ps -q -f name=$CONTAINER_NAME)" ]; then
              docker stop $CONTAINER_NAME
              docker rm $CONTAINER_NAME
            fi

            # Remove old images to save space
            if [ "$(docker images -q $IMAGE_NAME)" ]; then
              docker rmi -f $IMAGE_NAME
            fi

            # Build new Docker image
            docker build --pull -t $IMAGE_NAME .

            # Run new container with restart policy
            docker run -d --name $CONTAINER_NAME -p 3000:3000 --restart unless-stopped $IMAGE_NAME

            echo "Deployment to master branch completed successfully."
