name: Deploy to Production

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build project
        run: npm run build

      - name: Archive build
        run: tar -czf build.tar.gz ./

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: project-build
          path: build.tar.gz

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: project-build
          path: ./build

      - name: Deploy with Docker via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          timeout: 300s
          script: |
            # Navigate to project directory
            cd ~/htdocs/www.rangaone.finance/Rangaone_Finance || mkdir -p ~/htdocs/www.rangaone.finance/Rangaone_Finance && cd $_

            # Stop existing Docker container if running
            docker stop nextjs-app 2>/dev/null || true
            docker rm nextjs-app 2>/dev/null || true

            # Remove old code
            rm -rf ./*

            # Copy build from GitHub Actions
            tar -xzf build/build.tar.gz -C ./

            # Build and run Docker container
            docker build -t nextjs-app .
            docker run -d \
              --name nextjs-app \
              --restart unless-stopped \
              -p 3000:3000 \
              nextjs-app

            # Cleanup unused Docker images
            docker image prune -f

            echo "✅ Deployment complete!"
