name: Deploy to Production

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build and Deploy via SSH
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/${{ secrets.USERNAME }}/htdocs/${{ secrets.DOMAIN }}
          
          # Clean up existing files (force remove)
          sudo rm -rf .next node_modules package-lock.json || true
          
          # Pull latest code
          git fetch --all
          git reset --hard origin/main
          
          # Build and run with Docker
          docker-compose -f docker-compose.prod.yml down || true
          docker-compose -f docker-compose.prod.yml build --no-cache
          docker-compose -f docker-compose.prod.yml up -d
          
          # Verify deployment
          sleep 10
          curl -f http://localhost:3000 || exit 1