name: PM2 Deploy to Domain

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to CloudPanel
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/cloudpanel/htdocs/${{ secrets.DOMAIN_NAME }}
            git pull origin main
            npm install --production
            npm run build
            pm2 restart rangaone-fe || pm2 start npm --name "rangaone-fe" -- start