name: Simple Deploy to Domain

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-to-domain:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Domain Folder
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.CLOUDPANEL_HOST }}
          port: 22
          username: ${{ secrets.CLOUDPANEL_USER }}
          password: ${{ secrets.CLOUDPANEL_PASSWORD }}
          timeout: 300s
          command_timeout: 300s
          script: |
            # Set domain path
            export DOMAIN_PATH="/home/${{ secrets.CLOUDPANEL_USER }}/htdocs/${{ secrets.CLOUDPANEL_DOMAIN }}"
            
            # Create temp directory for deployment
            TEMP_DIR="/tmp/rangaone-deploy-$(date +%s)"
            mkdir -p $TEMP_DIR
            cd $TEMP_DIR
            
            # Clone repository
            git clone https://github.com/${{ github.repository }} .
            
            # Make deployment script executable
            chmod +x deploy-to-domain.sh
            
            # Run deployment script
            ./deploy-to-domain.sh
            
            # Cleanup temp directory
            cd /
            rm -rf $TEMP_DIR
            
            echo "✅ Deployment to domain folder completed successfully!"
      
      - name: Notify Deployment Status
        if: always()
        run: |
          if [ "${{ job.status }}" == "success" ]; then
            echo "🎉 Deployment successful!"
          else
            echo "❌ Deployment failed!"
          fi